create table public.entity (
  id bigint generated by default as identity not null,
  "EntityName" text not null,
  created_on timestamp with time zone not null default now(),
  updated_on timestamp without time zone null default now(),
  created_by timestamp without time zone null default now(),
  updated_by timestamp without time zone null default now(),
  constraint Entities_pkey primary key (id),
  constraint Entities_EntityName_key unique ("EntityName")
) TABLESPACE pg_default;

create table public.metadata (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  "entityId" bigint not null,
  filterable boolean null,
  sortable boolean null,
  type text null default 'string'::text,
  value text null,
  constraint metadata_pkey primary key (id),
  constraint metadata_entityId_fkey foreign KEY ("entityId") references entity (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;


INSERT INTO "public"."entity" ("EntityName") VALUES 
('address'), 
('cart'), 
('category'), 
('customer'), 
('favourite'), 
('gst'), 
('invoice'), 
('order'), 
('orderitem'), 
('payment'), 
('product'), 
('promo_code'), 
('role'), 
('shipment'), 
('status'), 
('variant'), 
('entity'), 
('metadata');

INSERT INTO public.metadata ("entityId", filterable, sortable, type, value) VALUES
  -- address (id: 1)
  (1, true, true, 'string', 'street'),
  (1, true, true, 'string', 'city'),
  (1, true, true, 'string', 'state'),
  (1, true, true, 'string', 'zip'),

  -- cart (id: 2)
  (2, false, false, 'string', 'cart_id'),
  (2, true, false, 'number', 'quantity'),

  -- category (id: 3)
  (3, true, true, 'string', 'name'),
  (3, true, false, 'string', 'description'),

  -- customer (id: 4)
  (4, true, true, 'string', 'first_name'),
  (4, true, true, 'string', 'last_name'),
  (4, true, false, 'string', 'email'),

  -- favourite (id: 5)
  (5, false, false, 'string', 'user_id'),
  (5, false, false, 'string', 'product_id'),

  -- gst (id: 6)
  (6, true, false, 'number', 'percentage'),

  -- invoice (id: 7)
  (7, true, true, 'string', 'invoice_number'),
  (7, true, true, 'timestamp', 'date'),

  -- order (id: 8)
  (8, true, true, 'string', 'order_number'),
  (8, true, true, 'timestamp', 'order_date'),
  (8, true, true, 'string', 'status'),

  -- orderitem (id: 9)
  (9, false, true, 'string', 'product_id'),
  (9, true, true, 'number', 'quantity'),

  -- payment (id: 10)
  (10, true, true, 'string', 'payment_method'),
  (10, true, true, 'number', 'payment_amount'),

  -- product (id: 11)
  (11, true, true, 'string', 'name'),
  (11, true, true, 'number', 'price'),
  (11, true, false, 'string', 'category'),

  -- promocode (id: 12)
  (12, true, true, 'string', 'code'),
  (12, true, true, 'number', 'discount'),

  -- role (id: 13)
  (13, true, true, 'string', 'role_name'),

  -- shipment (id: 14)
  (14, true, true, 'string', 'shipment_type'),
  (14, true, true, 'string', 'provider'),

  -- status (id: 15)
  (15, true, true, 'string', 'status_name'),

  -- variant (id: 16)
  (16, true, true, 'string', 'sku'),
  (16, true, true, 'string', 'size'),
  (16, true, true, 'string', 'color'),
  (16, true, true, 'number', 'price'),
  (16, true, true, 'boolean', 'is_default');



INSERT INTO "public"."metadata" ("entityId", "filterable", "sortable", "type", "value") VALUES 
('1', 'true', 'true', 'string', 'street'), 
('1', 'true', 'true', 'string', 'city'),
('1', 'true', 'true', 'string', 'state'), 
('1', 'true', 'true', 'string', 'zip'), 
('2', 'false', 'false', 'string', 'cart_id'), 
('2', 'true', 'false', 'number', 'quantity'), 
('3', 'true', 'true', 'string', 'name'), 
('3', 'true', 'false', 'string', 'description'), 
('4', 'true', 'true', 'string', 'first_name'), 
('4', 'true', 'true', 'string', 'last_name'), 
('4', 'true', 'false', 'string', 'email'), 
('5', 'false', 'false', 'string', 'user_id'), 
('5', 'false', 'false', 'string', 'product_id'), 
('6', 'true', 'false', 'number', 'percentage'), 
('7', 'true', 'true', 'string', 'invoice_number'), 
('7', 'true', 'true', 'timestamp', 'date'), 
('8', 'true', 'true', 'string', 'order_number'), 
('8', 'true', 'true', 'timestamp', 'order_date'), 
('8', 'true', 'true', 'string', 'status'), 
('9', 'false', 'true', 'string', 'product_id'), 
('9', 'true', 'true', 'number', 'quantity'), 
('10', 'true', 'true', 'string', 'payment_method'), 
('10', 'true', 'true', 'number', 'payment_amount'), 
('11', 'true', 'true', 'string', 'name'), 
('11', 'true', 'true', 'number', 'price'), 
('11', 'true', 'false', 'string', 'category'), 
('12', 'true', 'true', 'string', 'code'), 
('12', 'true', 'true', 'number', 'discount'), 
('13', 'true', 'true', 'string', 'role_name'), 
('14', 'true', 'true', 'string', 'shipment_type'), 
('14', 'true', 'true', 'string', 'provider'), 
('15', 'true', 'true', 'string', 'status_name'), 
('16', 'true', 'true', 'string', 'sku'), 
('16', 'true', 'true', 'string', 'size'), 
('16', 'true', 'true', 'string', 'color'), 
('16', 'true', 'true', 'number', 'price'), 
('16', 'true', 'true', 'boolean', 'is_default'), 
('11', 'true', 'true', 'string', 'description');