create table public.entity (
  id bigint generated by default as identity not null,
  "EntityName" text not null,
  created_on timestamp with time zone not null default now(),
  updated_on timestamp without time zone null default now(),
  created_by timestamp without time zone null default now(),
  updated_by timestamp without time zone null default now(),
  constraint Entities_pkey primary key (id),
  constraint Entities_EntityName_key unique ("EntityName")
) TABLESPACE pg_default;

create table public.metadata (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  "entityId" bigint not null,
  filterable boolean null,
  sortable boolean null,
  type text null default 'string'::text,
  value text null,
  constraint metadata_pkey primary key (id),
  constraint metadata_entityId_fkey foreign KEY ("entityId") references entity (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;


INSERT INTO "public"."entity" ("id", "EntityName", "created_on", "updated_on", "created_by", "updated_by") VALUES 
    ('1', 'address', '2025-10-19 08:11:34.293335+00', '2025-10-19 08:11:34.293335', '2025-10-19 08:11:34.293335', '2025-10-19 08:11:34.293335'), 
    ('2', 'cart', '2025-10-19 08:11:58.394537+00', '2025-10-19 08:11:58.394537', '2025-10-19 08:11:58.394537', '2025-10-19 08:11:58.394537'), 
    ('3', 'category', '2025-10-19 08:12:15.552916+00', '2025-10-19 08:12:15.552916', '2025-10-19 08:12:15.552916', '2025-10-19 08:12:15.552916'), 
    ('4', 'customer', '2025-10-19 08:12:32.327918+00', '2025-10-19 08:12:32.327918', '2025-10-19 08:12:32.327918', '2025-10-19 08:12:32.327918'), 
    ('5', 'favourite', '2025-10-19 08:12:41.515835+00', '2025-10-19 08:12:41.515835', '2025-10-19 08:12:41.515835', '2025-10-19 08:12:41.515835'), 
    ('6', 'gst', '2025-10-19 08:12:50.577596+00', '2025-10-19 08:12:50.577596', '2025-10-19 08:12:50.577596', '2025-10-19 08:12:50.577596'), 
    ('7', 'invoice', '2025-10-19 08:13:00.211384+00', '2025-10-19 08:13:00.211384', '2025-10-19 08:13:00.211384', '2025-10-19 08:13:00.211384'), 
    ('8', 'order', '2025-10-19 08:13:08.661541+00', '2025-10-19 08:13:08.661541', '2025-10-19 08:13:08.661541', '2025-10-19 08:13:08.661541'), 
    ('9', 'orderitem', '2025-10-19 08:13:16.997892+00', '2025-10-19 08:13:16.997892', '2025-10-19 08:13:16.997892', '2025-10-19 08:13:16.997892'), 
    ('10', 'payment', '2025-10-19 08:13:25.721664+00', '2025-10-19 08:13:25.721664', '2025-10-19 08:13:25.721664', '2025-10-19 08:13:25.721664'), 
    ('11', 'product', '2025-10-19 08:13:37.352569+00', '2025-10-19 08:13:37.352569', '2025-10-19 08:13:37.352569', '2025-10-19 08:13:37.352569'), 
    ('12', 'promo_code', '2025-10-19 08:13:50.186483+00', '2025-10-19 08:13:50.186483', '2025-10-19 08:13:50.186483', '2025-10-19 08:13:50.186483'), 
    ('13', 'role', '2025-10-19 08:14:00.00729+00', '2025-10-19 08:14:00.00729', '2025-10-19 08:14:00.00729', '2025-10-19 08:14:00.00729'), 
    ('14', 'shipment', '2025-10-19 08:14:06.67762+00', '2025-10-19 08:14:06.67762', '2025-10-19 08:14:06.67762', '2025-10-19 08:14:06.67762'), 
    ('15', 'status', '2025-10-19 08:14:13.473418+00', '2025-10-19 08:14:13.473418', '2025-10-19 08:14:13.473418', '2025-10-19 08:14:13.473418'), 
    ('16', 'variant', '2025-10-19 08:14:23.064667+00', '2025-10-19 08:14:23.064667', '2025-10-19 08:14:23.064667', '2025-10-19 08:14:23.064667');
    ('17', 'entity', '2025-10-19 08:14:23.064667+00', '2025-10-19 08:14:23.064667', '2025-10-19 08:14:23.064667', '2025-10-19 08:14:23.064667');
    ('18', 'metadata', '2025-10-19 08:14:23.064667+00', '2025-10-19 08:14:23.064667', '2025-10-19 08:14:23.064667', '2025-10-19 08:14:23.064667');


INSERT INTO public.metadata ("entityId", filterable, sortable, type, value) VALUES
  -- address (id: 1)
  (1, true, true, 'string', 'street'),
  (1, true, true, 'string', 'city'),
  (1, true, true, 'string', 'state'),
  (1, true, true, 'string', 'zip'),

  -- cart (id: 2)
  (2, false, false, 'string', 'cart_id'),
  (2, true, false, 'number', 'quantity'),

  -- category (id: 3)
  (3, true, true, 'string', 'name'),
  (3, true, false, 'string', 'description'),

  -- customer (id: 4)
  (4, true, true, 'string', 'first_name'),
  (4, true, true, 'string', 'last_name'),
  (4, true, false, 'string', 'email'),

  -- favourite (id: 5)
  (5, false, false, 'string', 'user_id'),
  (5, false, false, 'string', 'product_id'),

  -- gst (id: 6)
  (6, true, false, 'number', 'percentage'),

  -- invoice (id: 7)
  (7, true, true, 'string', 'invoice_number'),
  (7, true, true, 'timestamp', 'date'),

  -- order (id: 8)
  (8, true, true, 'string', 'order_number'),
  (8, true, true, 'timestamp', 'order_date'),
  (8, true, true, 'string', 'status'),

  -- orderitem (id: 9)
  (9, false, true, 'string', 'product_id'),
  (9, true, true, 'number', 'quantity'),

  -- payment (id: 10)
  (10, true, true, 'string', 'payment_method'),
  (10, true, true, 'number', 'payment_amount'),

  -- product (id: 11)
  (11, true, true, 'string', 'name'),
  (11, true, true, 'number', 'price'),
  (11, true, false, 'string', 'category'),

  -- promocode (id: 12)
  (12, true, true, 'string', 'code'),
  (12, true, true, 'number', 'discount'),

  -- role (id: 13)
  (13, true, true, 'string', 'role_name'),

  -- shipment (id: 14)
  (14, true, true, 'string', 'shipment_type'),
  (14, true, true, 'string', 'provider'),

  -- status (id: 15)
  (15, true, true, 'string', 'status_name'),

  -- variant (id: 16)
  (16, true, true, 'string', 'sku'),
  (16, true, true, 'string', 'size'),
  (16, true, true, 'string', 'color'),
  (16, true, true, 'number', 'price'),
  (16, true, true, 'boolean', 'is_default');
